Use relative units
DNepovim/strelka-frontend pull request #30
Opened 2022-02-20 19:53 UTC by smutnjo

2022-03-05 13:28 UTC, DNepovim requested changes

2022-03-05 13:28 UTC, DNepovim commented on packages/lib/src/ui/blocks/Header/Header.tsx
> +  height: ${theme.size.base * 3.8}rem;
Myslím, že čitelnejší a stejně relativní bude prosté `4.6rem`. Výsledek by měl být stejný.

2022-03-05 13:28 UTC, DNepovim commented on packages/lib/src/ui/blocks/Header/Header.tsx
> +    height: ${theme.size.base * 3.3}rem;
Viz výše

2022-03-05 13:28 UTC, DNepovim commented on packages/lib/src/ui/blocks/Header/Header.tsx
> +  font-size: ${theme.size.base * 1.25}rem;
Viz výše

2022-03-05 13:28 UTC, DNepovim commented on packages/lib/src/ui/blocks/Header/Header.tsx
> +  padding: 0.65rem 1.1rem;
Paddingy by možná měly být spíš v `em` aby byly relativní k velikosti písma přímo v něm. Ale nechám na tobě. Není to tak důležité.

2022-03-05 13:28 UTC, DNepovim commented on packages/lib/src/ui/components/MenuItemContent/MenuItemContent.tsx
> +  font-size: ${theme.size.base * 1.15}rem;
Vyz výše

2022-03-05 13:28 UTC, DNepovim commented on packages/lib/src/ui/components/MenuItemContent/MenuItemContent.tsx
> +  padding: 0.5rem 1em;
Proč máš jedno v `rem` a druhé v `em`?

2022-03-05 13:28 UTC, DNepovim commented on packages/lib/src/ui/components/MenuItemContent/MenuItemContent.tsx
> +    font-size: ${theme.size.base * 1.2}rem;
Viz výše

2022-03-05 13:28 UTC, DNepovim commented on packages/lib/src/ui/styles/theme.ts
> +  `(max-width: ${theme.breakpoints[breakpoint]}rem)`
Když bude teď šířka viewportu rovna hodnotě nějakého breakpointu, tak se budou aplikovat styly `min` i `max`, což neudělá dobrotu. Proto tam bylo to `- 1px`.

2022-03-06 17:32 UTC, DNepovim commented
Máš tam nějaké zvláštní počty. `theme.size.base * 3.8` měníš na `4.6r`. Ale `18 * 3,8` je `68,4`, což je úplně jiné číslo. Lícuje ti tam vše?

2022-03-08 21:39 UTC, smutnjo commented
> `theme.size.base * 3.8` měníš na `4.6`. Ale `18 * 3,8` je `68,4`, což je úplně jiné číslo.

velikost chci mít v `rem`, a theme.size.base je `1.2 rem`, proto `4.6 rem` (`1.2 * 3.8 = 4.6`)

2022-03-09 10:52 UTC, DNepovim approved these changes

2022-03-09 10:52 UTC, merged